#!/usr/bin/python3
import re
# import urlparse [Deprecated after Py2]
import urllib.parse as urlparse
import requests

base_url = "http://engineering.tech-corp.live/"
target_links = []


# subDomain = []
# longURL = []


# def request(url):
#     try:
#         return requests.get("http://" + url)
#         # print(get_response)
#     except requests.exceptions.ConnectionError:
#         pass

def extract_links_from(url):
    response = requests.get(base_url)
    return re.findall('(?:href=")(.*?)"', response.content.decode(errors="ignore"))


def crawl(url):
    href_links = extract_links_from(url)
    for link in href_links:
        link = urlparse.urljoin(url, link)
        if "#" in link:
            link = link.split("#")[0]
        if base_url in link and link not in target_links:
            target_links.append(link)
            print(link)
            crawl(link)


crawl(base_url)
