#!/usr/bin/env python
import requests

base_url = "subdomain.domain.(com or in or org or net)"
subDomain = []
longURL = []

def request(url):
    try:
        return requests.get("http://" + url)
        # print(get_response)
    except requests.exceptions.ConnectionError:
        pass


def subdomain():
    with open("/absolute path of the wordlist to discover subdomains", "r") as wordlist_file:
        for line in wordlist_file:
            word = line.strip()
            target_url = word + "." + base_url
            response = request(target_url)
            if response:
                subDomain.append(target_url)
                print("[+] Subdomain Discovered :" + target_url)


def long_url():
    with open("/absolute path of the wordlist to discover subdomains", "r") as wordlist_file:
        for line in wordlist_file:
            word = line.strip()
            target_url = base_url + "/" + word
            response = request(target_url)
            if response:
                longURL.append(target_url)
                print("[+] URL Discovered :" + target_url)
