#!/usr/bin/env python
import requests
import urllib.parse as urlparse
import re
from BeautifulSoup import BeautifulSoup


class Scanner:
    def __init__(self, url, ignore_links):
        self.session = requests.Session()
        self.target_url = url
        self.target_links = []
        self.links_to_ignore = ignore_links

    def extract_links_from(self, url):
        response = self.session.get(url)
        return re.findall('(?:href=")(.*?)"', response.content.decode(errors="ignore"))

    def crawl(self, url=None):
        if url is None:
            url = self.target_url
        href_links = self.extract_links_from(url)
        for link in href_links:
            link = urlparse.urljoin(url, link)
            if "#" in link:
                link = link.split("#")[0]
            if self.target_url in link and link not in self.target_links and link not in self.links_to_ignore:
                self.target_links.append(link)
                print(link)
                self.crawl(link)

    def extract_forms(self, url):
        response = self.session.get(url)
        parsed_html = BeautifulSoup(response.content)
        return parsed_html.findAll("form")

    def submit_forms(self, form, value, url):
        action = form.get("action")
        post_url = urlparse.urljoin(url, action)
        method = form.get("method")
        input_list = form.get("input")
        post_data = {}
        for input in input_list:
            input_name = input.get("name")
            input_type = input.get("type")
            input_value = input.get("value")
            if input_type == "text":
                input_value = value
            post_data[input_name] = input_value
        if method == "post":
            return requests.post(post_url, data=post_data)
        return self.session.get(post_url, params=post_data)

    def run_scanner(self):
        for link in self.target_links:
            forms = self.extract_forms(link)
            for form in forms:
                print("[+] Testing form in " + link)
                xss_vulnerable = self.xss_form(form, link)
                if xss_vulnerable:
                    print("\n\n[**] XSS Discovered in link : " + link)
                    print("[**] XSS Discovered in form : " + form)
            if "=" in link:
                print("[+] Testing " + link)
                xss_vulnerable = self.xss_link(link)
                if xss_vulnerable:
                    print("\n\n[**] XSS Discovered in link : " + link)

    def xss_link(self, url):
        xss_script = "<script>alert('test')</script>"
        url = url.replace("=", "=" + xss_script)
        response = self.session.get(url)
        return xss_script in response.content.decode()

    def xss_form(self, form, url):
        xss_script = "<script>alert('test')</script>"
        response = self.submit_forms(form, xss_script, url)
        return xss_script in response.content.decode()
